name: Build and Deploy Jekyll site to Pages
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec jekyll build -d _site
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
